#!/usr/bin/env bash
# A Bash script that runs infinitely and handles SIGTERM gracefully

# Trap SIGTERM and display message instead of terminating
trap "echo 'I am invincible!!!'" SIGTERM

# Infinite loop with message
while true
do
    echo "To infinity and beyond"
    sleep 2
done
